- name: Configurar servidor web
  hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar archivos HTML
      copy:
        src: /path/to/your/index.html
        dest: /var/www/html/index.html
