name: Run Tests

on:
  push:
    branches:
      - main # Cambia esto al nombre de tu rama principal si es diferente (por ejemplo, 'master')
  pull_request:
    branches:
      - main # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Usa la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
